triggers:
  '2016': &triggers_UL16
    - QuadJet45_TripleBTagCSV_p087
    - DoubleJet90_Double30_TripleBTagCSV_p087
  UL16_postVFP: *triggers_UL16
  UL16_preVFP: *triggers_UL16
  '2017': &triggers_UL17_basic
    - PFHT300PT30_QuadPFJet_75_60_45_40_TriplePFBTagCSV_3p0
  UL17: &triggers_UL17
    - HT300PT30_QuadJet_75_60_45_40_TripleCSV_p07
    - HT300PT30_QuadJet_75_60_45_40_TripeCSV_p07
    - PFHT300PT30_QuadPFJet_75_60_45_40_TriplePFBTagCSV_3p0
  UL18: &triggers_UL18
    - PFHT330PT30_QuadPFJet_75_60_45_40_TriplePFBTagDeepCSV_4p5
  '2018': *triggers_UL18
  
  # Run3 triggers
  2022_EE: &triggers_2022
    - QuadPFJet70_50_40_35_PFBTagParticleNet_2BTagSum0p65
    - PFHT330PT30_QuadPFJet_75_60_45_40_TriplePFBTagDeepJet_4p5
    - PFHT1050
  2022_preEE: *triggers_2022
  2023_BPix: &triggers_2023
    - QuadPFJet70_50_40_35_PNet2BTagMean0p65
    - PFHT280_QuadPFJet30_PNet2BTagMean0p55
    - PFHT330PT30_QuadPFJet_75_60_45_40_TriplePFBTagDeepJet_4p5
  2023_preBPix: *triggers_2023
