workflow:
  rules:
    # here the order matter!
    # it runs with merge requests
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # does not run with changes in .md files
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BEFORE_SHA !~ /0{40}/'
      changes:
        - "{*[^.]md*,*.[^m]*,*.m,*.m[^d]*,*.md?*,*[^d]}"
      when: never
    # does not run when creating tags
    - if: $CI_COMMIT_TAG
      when: never
    # does not run if branches start with test_
    - if: $CI_COMMIT_BRANCH =~ /test_/
      when: never
    # it runs with any branch
    - if: $CI_COMMIT_BRANCH

variables:
  CONTAINER_HOST: cms-cmu
  RECREATE_CONTAINERS: "false"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_FORCE_HTTPS: "true"

include:
  - local: '.ci-workflows/stages_*.yml'

stages:  
  - validation
  - pages
  - build
  - proxy
  - code 
  - skimmer-test
  - friendtree-test
  - analysis-test
  - fits
  - plot
  - cutflow
  - classifier
  - reana

.base_analysis:
  needs:
    - voms_proxy
  image: gitlab-registry.cern.ch/$CONTAINER_HOST/coffea4bees:latest
  tags:
    - k8s-cvmfs
  artifacts: 
    expire_in: 1 day
    paths:
      - 'template'
  before_script:
    - cd python/
  retry: 2

.base_combine:
  image: gitlab-registry.cern.ch/cms-analysis/general/combine-container:CMSSW_11_3_4-combine_v9.1.0-harvester_v2.1.0
  before_script:
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - cd /home/cmsusr/CMSSW_11_3_4/
    - cmsenv || true
    - cd -
    - cd python/
  tags:
    - k8s-cvmfs

.base_classifier:
  needs:
    - voms_proxy
  image: registry.hub.docker.com/chuyuanliu/heptools:ml-cpu # TODO change to central repo
  before_script:
    - source /entrypoint.sh
  tags:
    - k8s-cvmfs
  artifacts:
    expire_in: 1 day

include:
  - project: 'authoring/documentation/mkdocs-ci'
    file: 'mkdocs-gitlab-pages.gitlab-ci.yml'

variables:
  MKDOCS_VERSION: '1.5.3'
  MATERIAL_VERSION: '9.5.3'

