workflow:
  rules:
    # This rule explicitly allows manual triggers (from the web UI)
    # as long as they are not on a tag or a 'test' branch.
    - if: $CI_PIPELINE_SOURCE == 'web' && $CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH !~ /test/
      when: always

    # Do not run for tags (this will catch both push and manual if not already excluded)
    - if: $CI_COMMIT_TAG
      when: never

    # Do not run for branches with 'test' in the name (likewise)
    - if: $CI_COMMIT_BRANCH =~ /test/
      when: never

    # Do not run if only markdown files changed (for pushes/MRs, not typically for manual)
    - changes:
        - "**/*.md"
      when: never

    # Run for merge request events
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always

    # Run for all other branch pushes (the default push behavior)
    - if: $CI_COMMIT_BRANCH
      when: always

    # Default to never if no other rule matches
    - when: never

variables:
  CONTAINER_HOST: cms-cmu
  RECREATE_CONTAINERS: "false"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  MKDOCS_VERSION: '1.5.3'
  MATERIAL_VERSION: '9.5.3'

include:
  - local: '.ci-workflows/stages_*.yml'
  - project: 'authoring/documentation/mkdocs-ci'
    file: 'mkdocs-gitlab-pages.gitlab-ci.yml'

stages:  
  - build
  - proxy
  - code 
  - skimmer-test
  - friendtree-test
  - analysis-test
  - fits
  - plot
  - cutflow
  - classifier
  - reana
  - deploy
  - validation
  - pages

validation:
  rules:
    - changes:
      - docs/**

pages:
  rules:
    - changes:
      - docs/**
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.base_analysis:
  needs:
    - voms_proxy
  image: ${CI_REGISTRY_IMAGE}:test
  tags:
    - k8s-cvmfs
  artifacts: 
    expire_in: 1 day
    paths:
      - 'template'
  before_script:
    - cd python/
  retry: 2

.base_combine:
  image: gitlab-registry.cern.ch/cms-analysis/general/combine-container:CMSSW_11_3_4-combine_v9.1.0-harvester_v2.1.0
  before_script:
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - cd /home/cmsusr/CMSSW_11_3_4/
    - cmsenv || true
    - cd -
    - cd python/
  tags:
    - k8s-cvmfs

.base_classifier:
  needs:
    - voms_proxy
  image: registry.hub.docker.com/chuyuanliu/heptools:ml-cpu # TODO change to central repo
  before_script:
    - source /entrypoint.sh
  tags:
    - k8s-cvmfs
  artifacts:
    expire_in: 1 day



