workflow:
  rules:
    # here the order matter!
    # does not run with changes in .md files
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BEFORE_SHA !~ /0{40}/'
      changes:
        - "{*[^.]md*,*.[^m]*,*.m,*.m[^d]*,*.md?*,*[^d]}"
      when: never
    # does not run when creating tags
    - if: $CI_COMMIT_TAG
      when: never
    # does not run if branches start with test_
    - if: $CI_COMMIT_BRANCH =~ /test_/
      when: never
    # it runs with any branch
    - if: $CI_COMMIT_BRANCH

variables:
  CONTAINER_HOST: cms-cmu
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_FORCE_HTTPS: "true"

include:
  - local: '.ci-workflows/stages_*.yml'

stages:          
  - build
  - proxy
  - skimmer-test
  - analysis-test	
  - cutflow

.base_analysis:
  needs:
    - voms_proxy
  image: gitlab-registry.cern.ch/$CONTAINER_HOST/coffea4bees:latest
  tags:
    - k8s-cvmfs
  artifacts: 
    expire_in: 1 day
    paths:
      - 'template'

.base_combine:
  image: gitlab-registry.cern.ch/cms-analysis/general/combine-container:CMSSW_11_3_4-combine_v9.1.0-harvester_v2.1.0
  before_script:
    - source /cvmfs/cms.cern.ch/cmsset_default.sh
    - cd /home/cmsusr/CMSSW_11_3_4/
    - cmsenv || true
    - cd -
  tags:
    - k8s-cvmfs
