main:
  module: cache
  option:
    - --max-writers 4
    - --nchunks 6

dataset:
  - module: HCR.FvT_picoAOD
    option:
      - --friends ""
      - root://cmseos.fnal.gov//store/user/chuyuanl/HH4b/friend/friends.json@@HCR_input
      - root://cmseos.fnal.gov//store/user/chuyuanl/HH4b/friend/friends.json@@JCM_weight
      - --max-workers 8