main:
  module: train
  option:
    - --max-loaders 3 # match the number of dataset loaders
    - --max-trainers 1 # train 1 model at a time for testing

model:
  - module: HCR.FvT
    option:
      - --kfolds 3
      - --kfold-offsets 0 # use 1 offset out 3 for testing
      - --training FixedStep # setup training schedule
      - epoch: 1 # training for 1 epoch for testing
        bs_init: 1024
      - --kfold-seed data # setup initial seed for random dataset splitter
      - --kfold-seed-offsets 0-4 # generate 5 seeds from the initial seed to get uncorrelated subsets
