analysis-cutflow-job:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow-job.sh
  artifacts:
    paths:
      - output/analysis_cutflow_job/test_dump_cutflow.yml

analysis-cutflow-job-Run3:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_Run3_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow-job-Run3.sh
  artifacts:
    paths:
      - output/analysis_cutflow_job_Run3/test_dump_cutflow.yml


analysis-mixed-cutflow-job:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_mixed_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-mixed-cutflow-job.sh
  artifacts:
    paths:
      - output/analysis_mixed_cutflow_job/test_dump_cutflow_mixed_data.yml
      - output/analysis_mixed_cutflow_job/test_dump_cutflow_mixed_bkg.yml

skimmer-analysis-cutflow-job:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - skimmer_analysis_test_coffea4bees
  script:
    - source coffea4bees/scripts/skimmer-analysis-cutflow-job.sh
  artifacts:
    paths:
      - output/skimmer_analysis_cutflow_job/test_dump_skimmer_cutflow.yml
  # allow_failure: true

analysis-systematics-cutflow-job:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_systematics_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-systematics-cutflow-job.sh
  artifacts:
    paths:
      - output/analysis_systematics_cutflow_job/test_dump_systematics_cutflow.yml

analysis-cutflow-job-unsup:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_unsup_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow-job-unsup.sh
  artifacts:
    paths:
      - output/analysis_cutflow_job_unsup/test_dump_cutflow_job_unsup.yml

synthetic-dataset-analyze-cutflow:
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - synthetic-dataset-analyze
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-cutflow.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_cutflow/test_dump_cutflow_synthetic_datasets.yml

synthetic-dataset-analyze-cutflow-Run3:
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - synthetic-dataset-analyze-Run3
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-cutflow-Run3.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_cutflow_Run3/test_dump_cutflow_synthetic_datasets.yml


weights-trigger-cutflow:
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - weights_trigger_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/weights-trigger-cutflow-job.sh
  artifacts:
    paths:
      - output/weights_trigger_cutflow_job/test_dump_cutflow_trigWeight.yml

SvB-friendtree-cutflow-job:
  stage: cutflow
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - SvB_friendtree_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/SvB-friendtree-cutflow-job.sh
  artifacts:
    paths:
      - output/SvB_friendtree_cutflow_job/test_dump_cutflow_SvB_friend.yml

analysis-cutflow-dilepttbar-job:    
  stage: cutflow
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow-dilepttbar-job.sh
  artifacts:
    paths:
      - output/analysis_cutflow_dilepttbar_job/test_dump_cutflow.yml