analysis_plot_coffea4bees:    
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_plot/RunII/

analysis-plot-job-unsup:    
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_unsup_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-plot-job-unsup.sh
  artifacts:
    paths:
      - output/analysis_plot_job_unsup/RunII/

analysis_iplot_coffea4bees:
  stage: plot 
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-iplot.sh --output-base /builds/$CI_PROJECT_PATH/output

baseclass-test-job:   
  stage: plot
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/baseclass-test-job.sh

# Needs review
# histtojson-test-job:   
#   stage: plot
#   extends:
#     - .base_analysis
#   needs: 
#     - tools_merge_test_coffea4bees
#   script:
#     - cd stats_analysis/
#     - python convert_hist_to_json.py -o hists/histAll.json -i ../analysis/hists/test.coffea
#   artifacts: 
#     paths:
#       - stats_analysis/hists/histAll.json

synthetic-dataset-plot-job:    
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - synthetic_dataset_cluster_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-plot-job.sh
  artifacts:
    paths:
      - output/synthetic_dataset_plot_job/jet-splitting-PDFs-test/
