analysis_plot_coffea4bees:    
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_plot/RunII/

analysis_plot_unsup_coffea4bees:
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_test_unsup_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-plot-unsup.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_plot_unsup/RunII/

analysis_iplot_coffea4bees:
  stage: plot 
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-iplot.sh --output-base /builds/$CI_PROJECT_PATH/output

code_plot_test_coffea4bees:
  stage: plot
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/code-plot-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/code_plot_test/test_dumpPlotCounts.yml

synthetic_dataset_plot_coffea4bees:
  stage: plot
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - synthetic_dataset_cluster_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_plot/jet-splitting-PDFs-test/
