analysis_test_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test/test_databkgs.coffea

analysis_signals_test_coffea4bees:
  stage: analysis
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-signals-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_signals_test/test_signal.coffea

analysis_test_Run3_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-Run3.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_Run3/test.coffea

analysis_truthStudy_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-truthStudy-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_truthStudy_test/testTruth.coffea


synthetic_dataset_cluster_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/synthetic-dataset-cluster.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/synthetic_dataset_cluster/test_synthetic_datasets.coffea

analysis_test_unsup_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-unsup.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_unsup/test_unsup.coffea

analysis_test_mixed_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-mixed.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_mixed/testMixedBkg_TT.coffea
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed.coffea
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed_kfold.coffea
      - output/analysis_test_mixed/testMixedData.coffea
      - output/analysis_test_mixed/testMixedBkg_TT.json
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed.json
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed_kfold.json      
      - output/analysis_test_mixed/testMixedData.json
      - output/analysis_test_mixed/testSignal_preUL.coffea
      - output/analysis_test_mixed/testSignal_preUL.json
      - output/analysis_test_mixed/testSignal_UL.coffea
      - output/analysis_test_mixed/testSignal_UL.json

analysis_systematics_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-systematics-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_systematics_test/test_systematics.coffea

skimmer_analysis_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - skimmer_test_coffea4bees
  script:
    - source coffea4bees/scripts/skimmer-analysis-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/skimmer_analysis_test/test_skimmer.coffea

synthetic-dataset-analyze:   
  stage: analysis   
  extends:
    - .base_analysis
    - setup_workspace
  needs:
    - voms_proxy
    - synthetic_dataset_make_dataset_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze/test_synthetic_datasets.coffea

synthetic-dataset-analyze-Run3:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - setup_workspace
    - synthetic_dataset_make_dataset_Run3_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-Run3.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_Run3/test_synthetic_datasets.coffea


weights-trigger-analysis-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - setup_workspace
    - weights_trigger_friendtree_coffea4bees
  script:
    - source coffea4bees/scripts/weights-trigger-analysis-job.sh
  artifacts:
    paths:
      - output/weights_trigger_analysis_job/test_trigWeight.coffea

SvB-friendtree-analysis-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - setup_workspace
    - SvB_friendtree_coffea4bees
  script:
    - source coffea4bees/scripts/SvB-friendtree-analysis-job.sh
  artifacts:
    paths:
      - output/SvB_friendtree_analysis_job/test_SvB_friend.coffea

memory_test_coffea4bees:
  stage: analysis
  needs:
    - voms_proxy
    - setup_workspace
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/memory_test.sh
  allow_failure: true
  artifacts:
    paths:
      - output/memory_test/mprofile_ci_test.png
