analysis-test-job:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-job.sh
  artifacts: 
    paths:
      - output/analysis_test_job/test_databkgs.coffea

analysis-signals-test-job:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-signals-test-job.sh
  artifacts: 
    paths:
      - output/analysis_signals_test_job/test_signal.coffea

analysis-merge-test-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - analysis-test-job
    - analysis-signals-test-job
  script:
    - source coffea4bees/scripts/analysis-merge-test-job.sh
  artifacts: 
    paths:
      - output/analysis_merge_test_job/test.coffea

analysis-test-job-Run3:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-job-Run3.sh
  artifacts: 
    paths:
      - output/analysis_test_job_Run3/test.coffea


analysis-test-job-truthStudy:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-job-truthStudy.sh
  artifacts: 
    paths:
      - output/analysis_test_truthStudy/testTruth.coffea


synthetic-dataset-cluster:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/synthetic-dataset-cluster.sh
  artifacts: 
    paths:
      - output/synthetic_dataset_cluster/test_synthetic_datasets.coffea


analysis-test-job-unsup:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-job-unsup.sh
  artifacts: 
    paths:
      - output/analysis_test_job_unsup/test_unsup.coffea

analysis-test-mixed-job:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-test-mixed-job.sh
  artifacts: 
    paths:
      - output/analysis_test_mixed_job/testMixedBkg_TT.coffea
      - output/analysis_test_mixed_job/testMixedBkg_data_3b_for_mixed.coffea
      - output/analysis_test_mixed_job/testMixedBkg_data_3b_for_mixed_kfold.coffea
      - output/analysis_test_mixed_job/testMixedData.coffea
      - output/analysis_test_mixed_job/testMixedBkg_TT.json
      - output/analysis_test_mixed_job/testMixedBkg_data_3b_for_mixed.json
      - output/analysis_test_mixed_job/testMixedBkg_data_3b_for_mixed_kfold.json      
      - output/analysis_test_mixed_job/testMixedData.json
      - output/analysis_test_mixed_job/testSignal_preUL.coffea
      - output/analysis_test_mixed_job/testSignal_preUL.json
      - output/analysis_test_mixed_job/testSignal_UL.coffea
      - output/analysis_test_mixed_job/testSignal_UL.json


analysis-systematics-test-job:   
  stage: analysis   
  extends:
    - .base_analysis
  script:
    - source coffea4bees/scripts/analysis-systematics-test-job.sh
  artifacts: 
    paths:
      - output/analysis_systematics_test_job/test_systematics.coffea

skimmer-analysis-test-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs: 
    - voms_proxy
    - skimmer-test-job
  script:
    - source coffea4bees/scripts/skimmer-analysis-test-job.sh
  artifacts: 
    paths:
      - output/skimmer_analysis_test_job/test_skimmer.coffea

synthetic-dataset-analyze:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - synthetic-dataset-make-dataset
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze/test_synthetic_datasets.coffea

synthetic-dataset-analyze-Run3:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - synthetic-dataset-make-dataset-Run3
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-Run3.sh
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_Run3/test_synthetic_datasets.coffea


weights-trigger-analysis-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - weights-trigger-friendtree-job
  script:
    - source coffea4bees/scripts/weights-trigger-analysis-job.sh
  artifacts:
    paths:
      - output/weights_trigger_analysis_job/test_trigWeight.coffea

SvB-friendtree-analysis-job:   
  stage: analysis   
  extends:
    - .base_analysis
  needs:
    - voms_proxy
    - SvB-friendtree-job
  script:
    - source coffea4bees/scripts/SvB-friendtree-analysis-job.sh
  artifacts:
    paths:
      - output/SvB_friendtree_analysis_job/test_SvB_friend.coffea