include:
  - local: workflows/gitlab-CI/stages_analysis-test.yml
  - local: workflows/gitlab-CI/stages_classifier.yml
  - local: workflows/gitlab-CI/stages_code.yml
  - local: workflows/gitlab-CI/stages_cutflow.yml
  - local: workflows/gitlab-CI/stages_fits.yml
  - local: workflows/gitlab-CI/stages_friendtree.yml
  - local: workflows/gitlab-CI/stages_plots.yml
  - local: workflows/gitlab-CI/stages_skimmer-test.yml