tools_merge_test_coffea4bees:
  stage: tools
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - analysis_test_coffea4bees
    - analysis_signals_test_coffea4bees
  script:
    - source coffea4bees/scripts/tools-merge-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/tools_merge_test/test.coffea

analysis-make-jcm-weights-job:    
  stage: tools
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-make-jcm-weights-job.sh
  artifacts:
    paths:
      - output/analysis_make_jcm_weights_job/testJCM_ROOT/jetCombinatoricModel_SB_.yml

twoStageClosure-test-job:   
  stage: tools
  extends:
    - .base_combine
  needs: 
    - setup_workspace
    - analysis-test-mixed-job
  script:
    - source coffea4bees/scripts/analysis-runTwoStageClosure-ROOT.sh

