# template:
# - model: path to model
# - SvB: path to friend tree

main:
  module: evaluate
  option:
    - --max-evaluators 3

model:
  - module: HCR.SvB.ggF.baseline.Eval
    option:
      - --models
      - Final
      - "{model}/result.json"

dataset:
  - module: HCR.SvB.Eval
    option:
      - --metadata datasets_HH4b_2024_v2
      - --max-workers 8
      - --friends "" metadata/datasets_HH4b_2024_v2_classifier_input.json@@HCR_input

analysis:
  - module: kfold.Merge
    option:
      - --name SvB
      - --step 100000
      - --workers 5
      - --clean

setting:
  - module: IO
    option:
      - output: "{SvB}"
  - module: ml.DataLoader
    option:
      - num_workers: 8
