# template:
# - mixed: mixed data index
# - offset: offset for kfold

model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets {offset}
      - --training FixedStep
      - epoch: 10
        bs_init: 1024
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384
# training set: mixed 4b + detector 3b + ttbar 4b + ttbar 3b
# SR(blinded) + SB; no JCM
# TODO: fix ttbar weight
dataset:
  - module: HCR.FvT.TrainBaseline
    option:
      - --no-JCM # remove JCM
      - --no-detector-4b
      - --data-source mixed detector
      - --data-mixed-samples {mixed}
      - --preprocess label:data
      - df.tools.add_columns
      - weight: 1.0
      - --max-workers 8