2024_v2:
  <discard>:
    timestamp <task=start_time><var>:
    taskname <code><var>: f"classifier_plot_2024_v2_{timestamp}"
    _scratch <task=join_path><var>:
      - <ref>: scratch_dir
      - tmp
      - <ref>: taskname
    _output <task=join_path><var>:
      - <ref>: output_dir
      - <ref>: taskname

  task_plot <task=apply><var>:
    processor <task=processors.classifier::BasicPlot>:
      JCM <task=weight::TightBTagJCM>:
        weights <file=absolute>: analysis/weights/JCM/2024_v2/jetCombinatoricModel_SB_2024_v2.yml#JCM_weights
    fileset <task=picoAOD>:
      metadata <file=absolute>: metadata/datasets_HH4b_2024_v2.yml#datasets
      datasets <ref>: classifier_datasets
    friend_trees:
      HCR_input <file=absolute>: metadata/datasets_HH4b_2024_v2_classifier_input.json#HCR_input
    friend_trees <ref><extend>: classifier_outputs

  tasks <extend>:
    - <task=dump_hists>:
        outputs:
          - <ref>: task_plot
        dumper <task=dumper>:
          url <output=hists/classifier_basic.coffea> <code>: _scratch / "classifier" / "BasicPlot.coffea"

  post-tasks:
    - <task=Outputs.collect>:
        base <ref>: _output
        clean: True
