default:
  UL18:
    - PFHT330PT30_QuadPFJet_75_60_45_40_TriplePFBTagDeepCSV_4p5
  UL17:
    - PFHT300PT30_QuadPFJet_75_60_45_40_TriplePFBTagCSV_3p0
  UL16 <var>:
    - QuadJet45_TripleBTagCSV_p087
    - DoubleJet90_Double30_TripleBTagCSV_p087
  UL16_postVFP <ref=copy>: UL16
  UL16_preVFP <ref=copy>: UL16
