# template:
# - model: path to model
# - FvT: path to friend tree

main:
  module: evaluate
  option:
    - --max-evaluators 3 # use 3 workers to evaluate

dataset:
  - module: HCR.FvT.Eval
    option:
      - --metadata datasets_HH4b_2024_v2
      - --max-workers 8 # use 8 workers to fetch metadatas for ROOT files
      - --data-source detector
      - --friends "" metadata/datasets_HH4b_2024_v2_classifier_input.json@@HCR_input

model:
  - module: HCR.FvT.baseline.Eval
    option:
      - --models
      - Final # choose name of the model to evaluate, for now only Final is available
      - "{model}/result.json" # setup the path to the training result

analysis:
  - module: kfold.Merge # merge different k-folds
    option:
      - --name FvT # set the name of friend tree
      - --step 100000 # set the step to read ROOT files
      - --workers 5
      - --clean # remove the original files

setting:
  - module: IO
    option:
      - output: "{FvT}"
  - module: ml.DataLoader
    option:
      - num_workers: 8
