# template:
# - mixed: mixed data index
# - offset: offset for kfold
# - user: lpc username
# - tag: tag of the model

main:
  module: train
  option:
    - --max-loaders 10
    - --max-trainers 3

model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets {offset}
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384
# training set: mixed 4b + detector 3b
# SB only; no JCM;
dataset:
  - module: HCR.FvT.TrainDataOnly
    option:
      - --no-JCM
      - --no-SR
      - --no-detector-4b
      - --data-source mixed detector
      - --data-mixed-samples {mixed}
      - --friends
      -
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@HCR_input
      - --max-workers 16

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/FvT/nott/{tag}-{mixed}/
  - module: torch.DataLoader
    option:
      - num_workers: 4
