stages:
  - name: runcode
    dependencies: [init]
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        workingdir: {step: init, output: workdir, unwrap: true}
      step: {$ref: '.ci-workflows/steps.yaml#/runcode'}
