model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets {offset}
      - --training FixedStep
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384
