model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets {offset}
      - --training FixedStep
      - epoch: 5
        bs_init: 2048
        bs_scale: 16
        bs_milestones:
          - 1
        lr_scale: 0.5
        lr_milestones:
          - 1
          - 2
          - 3
          - 4
      - --ghost-batch
      - n_batches: 0
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384
