hists:
  data: data_obs_closure__63
  fit: closure_TH1_basis0__64

stack:
  TTbar: ttbar_closure_stack_1
  Multijet: multijet_closure_stack_2


ratio:
  ratio_prefit: data_obs_closureratio_hist0dO8912203003111607__61
  ratio_postfit: data_obs_closureratio_hist0dO10596662507060561__62