hists:
  data: multijet_ensemble_average__24
  fit: multijet_ensemble_TH1_basis3__25

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO461611139805265__22
  ratio_postfit: multijet_ensemble_TH1_basis3ratio_hist0dO6955359554791848__23