hists:
  data: multijet_ensemble_average__10
  fit: multijet_ensemble_TH1_basis1__11

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO30455123824610253__8
  ratio_postfit: multijet_ensemble_TH1_basis1ratio_hist0dO7865119268687277__9