hists:
  data: multijet_ensemble_average__17
  fit: multijet_ensemble_TH1_basis2__18

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO9940191797182397__15
  ratio_postfit: multijet_ensemble_TH1_basis2ratio_hist0dO5603007809552223__16