hists:
  data: multijet_ensemble_average__38
  fit: multijet_ensemble_TH1_basis5__39

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO5471354620236666__36
  ratio_postfit: multijet_ensemble_TH1_basis5ratio_hist0dO8222404089633809__37