# template:
# - mixed: mixed data index
# - offset: offset for kfold
# - user: lpc username
# - tag: tag of the model

main:
  module: train
  option:
    - --max-loaders 2
    - --max-trainers 3

model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets {offset}
      - --training FixedStep
      - epoch: 5
        bs_init: 1024
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384
# TODO fix ttbar weight in friend tree
dataset:
  - module: HCR.FvT.TrainBaseline
    option:
      - --data-source mixed
      - --data-mixed-samples {mixed}
      - --JCM-weight # TODO load JCM weight
      - --friends
      -
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@HCR_input
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@JCM_weight
      - --max-workers 8
  - module: HCR.FvT.Train
    option:
      - --no-detector-4b
      - --JCM-weight # TODO load JCM weight
      - --branch pseudoTagWeight_3bDvTMix4bDvT_v{mixed}
      - --preprocess source:detector
      - compatibility.JCM.column.apply_JCM
      - name: pseudoTagWeight_3bDvTMix4bDvT_v{mixed}
      - --preprocess source:detector
      - df.tools.drop_columns
      - - pseudoTagWeight_3bDvTMix4bDvT_v{mixed}
      - --files "label:data,source:detector,year:2016" root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2016_3b/picoAOD_3b_wJCM_newSBDef.root
      - --files "label:data,source:detector,year:2017" root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2017_3b/picoAOD_3b_wJCM_newSBDef.root
      - --files "label:data,source:detector,year:2018" root://cmseos.fnal.gov//store/user/jda102/condor/ZH4b/ULTrig//data2018_3b/picoAOD_3b_wJCM_newSBDef.root
      - --max-workers 8
      - --friends
      -
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/tmp/data3b/friend.json@@HCR_input

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/FvT/baseline/{tag}-{mixed}/
  - module: ml.DataLoader
    option:
      - num_workers: 4
