hists:
  data: data_obs_closure__45
  fit: closure_TH1_basismI1__46

stack:
  TTbar: ttbar_closure_stack_1
  Multijet: multijet_closure_stack_2


ratio:
  ratio_prefit: data_obs_closureratio_hist0dO07709791481750361__43
  ratio_postfit: data_obs_closureratio_hist0dO3913000209798775__44