hists:
  data: histdataHHbb_2016__5
  HH4b: ggHH_kl_1_kt_1_13p0TeV_hbbhbb__7

stack:
  TTbar: tt_stack_1
  Multijet: multijet_stack_2

ratio:
  ratio_dataToBkg: histdataHHbb_2016__10
  band_dataToBkg: bkg_syst__9