# template:
# - model: path to model
# - FvT: path to friend tree

main:
  module: evaluate
  option:
    - --max-evaluators 3

dataset:
  - module: HCR.FvT.Eval
    option:
      - --metadata datasets_HH4b_2024_v2
      - --max-workers 8
      - --data-source detector # only evaluate on data
      - --friends "" metadata/datasets_HH4b_2024_v2_classifier_input.json@@HCR_input

model:
  - module: HCR.FvT.baseline.Eval
    option:
      - --models
      - Final
      - "{FvT}/result.json"

analysis:
  - module: kfold.Merge
    option:
      - --name SvB
      - --step 100000
      - --workers 5
      - --clean

setting:
  - module: IO
    option:
      - output: "{friend}"
  - module: ml.DataLoader
    option:
      - num_workers: 8
