# template:
# - user: lpc username

main:
  module: evaluate
  option:
    - --max-evaluators 3

dataset:
  - module: HCR.FvT.Eval
    option:
      - --metadata datasets_HH4b_2024_v2
      - --max-workers 8
      - --metadata datasets_HH4b
      - --data-source detector # only evaluate on data
      - --friends "" metadata/datasets_HH4b_2024_v2_classifier_input.json@@HCR_input

model:
  - module: HCR.FvT.baseline.Eval
    option:
      - --models
      - Final
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/HH4b_2024_v2/FvT/data/result.json

analysis:
  - module: kfold.Merge
    option:
      - --name SvB
      - --step 100000
      - --workers 5
      - --clean

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/HH4b_2024_v2/FvT/data/
  - module: ml.DataLoader
    option:
      - num_workers: 8
  - module: ROOT
    option:
      - friend_allow_missing: false
