# template:
# - user: lpc username

main:
  module: train
  option:
    - --max-loaders 2
    - --max-trainers 3

dataset:
  - module: HCR.FvT.TrainBaseline
    option:
      - --metadata datasets_HH4b_2024_v2
      - --max-workers 20
      - --data-source detector
      - --JCM-weight "" analysis/weights/JCM/2024_v2/jetCombinatoricModel_SB_2024_v2.yml@@JCM_weights
      - --friends "" metadata/datasets_HH4b_2024_v2_classifier_input.json@@HCR_input

model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets 0
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FixedStep
      - epoch: 1
        bs_init: 16384

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b_2024_v2/classifier/FvT/data/
