# template:
# - user: lpc username

main:
  module: evaluate
  option:
    - --max-evaluators 3

dataset:
  - module: HCR.FvT.Eval
    option:
      - --max-workers 8
      - --metadata datasets_HH4b
      - --data-source detector # only evaluate on data
      - --mc-processes # set mc-processes to empty (to remove ttbar)
      - --friends "" root://cmseos.fnal.gov//store/user/chuyuanl/HH4b/friend/AN_v3/FvT/friend.json@@HCR_input

model:
  - module: HCR.FvT.baseline.Eval
    option:
      - --models
      - Final
      - root://cmseos.fnal.gov//store/user/chuyuanl/HH4b/classifier/HH4b_v3/FvT/data/result.json

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/HH4b_v3/FvT/data/
  - module: ml.DataLoader
    option:
      - num_workers: 8
