main:
  module: train
  option:
    - --max-loaders 2
    - --max-trainers 3

model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets 0-14
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FixedStep
      - epoch: 1
        bs_init: 16384

analysis:
  - module: HCR.LossROC

setting:
  - module: ml.Training
    option:
      - disable_benchmark: true
  - module: ml.DataLoader
    option:
      - optimize_sliceable_dataset: true