setting:
  - module: ml.DataLoader
    option:
      - optimize_sliceable_dataset: true
  - module: ROOT
    option:
      - friend_allow_missing: false
  - module: cms.CollisionData
    option:
      - eras:
          UL18: [A, B, C, D]
  - module: HCR.InputBranch
    option:
      - feature_ancillary: [xW, nSelJets, xbW]
