2024_v2:
  <discard><comment=classifier_plot.cfg.yml>:
    classifier_outputs<var>:
      # the name starts with "SvB" or "FvT" will be interpreted as the corresponding classifier outputs
      SvB_nominal <code><file>: f"root://cmseos.fnal.gov//store/user/{lpc_username}/HH4b_2024_v2/friend/SvB/ggF_baseline/result.json#analysis.0.merged"
      FvT_nominal <code><file>: f"root://cmseos.fnal.gov//store/user/{lpc_username}/HH4b_2024_v2/friend/FvT/data/result.json#analysis.0.merged"
    classifier_datasets<var>:
      - <include>:
          - dataset.cfg.yml#HH4b_ggF
          - dataset.cfg.yml#ttbar
          - dataset.cfg.yml#ZX4b
        years:
          - UL18
      - processes: data
        years:
          UL18: [A, B, C, D]
