test_local_small:
  client<task=unique_client>:
    address <type=distributed::LocalCluster><var=_cluster>:
      n_workers: 0
      processes: true
      threads_per_worker: 1
      memory_limit: 2GB
      dashboard_address: :8787
    <discard><comment=adaptive>:
      <type=distributed::LocalCluster.adapt>:
        null:
          - <ref>: _cluster
        minimum: 0
        maximum: 8
        maximum_memory: 16GB

rogue_local_huge:
  client<task=unique_client>:
    address <type=distributed::LocalCluster><var=_cluster>:
      n_workers: 0
      processes: true
      threads_per_worker: 1
      memory_limit: 2GB
      dashboard_address: :8787
    <discard><comment=adaptive>:
      <type=distributed::LocalCluster.adapt>:
        null:
          - <ref>: _cluster
        minimum: 0
        maximum: 100
        maximum_memory: 200GB
