physics:
  br <var>:
    H->bb: 0.5824 # https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR
    Z->bb: 0.1512 # PDG
    W->hadrons <var>: 0.6741 # PDG
    t->hadrons <ref>: W->hadrons
  xs:
    13TeV: # Run2
      # https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWGHH
      GluGluToHHTo4B_cHHH0 <code>: 0.06856 * br["H->bb"]**2
      GluGluToHHTo4B_cHHH1 <code>: 0.03077 * br["H->bb"]**2
      GluGluToHHTo4B_cHHH2p45 <code>: 0.01347 * br["H->bb"]**2
      GluGluToHHTo4B_cHHH5 <code>: 0.09082 * br["H->bb"]**2
      # https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageAt13TeV
      ZH4b <code>: 0.7612 * br["Z->bb"] * br["H->bb"]
      ggZH4b <code>: 0.1227 * br["Z->bb"] * br["H->bb"]
      # https://arxiv.org/pdf/2009.01186
      ZZ4b <code>: 17.4 * br["Z->bb"]**2
      # https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO
      TTJets <var>: 831.76
      TTToHadronic <code>: TTJets * br["t->hadrons"]**2
      TTToSemiLeptonic <code>: TTJets * 2 * br["t->hadrons"] * (1-br["t->hadrons"])
      TTTo2L2Nu <code>: TTJets * (1-br["t->hadrons"])**2
  lumi:
    UL16_postVFP: 16.5e+3
    UL16_preVFP: 19.5e+3
    UL17: 41.5e+3
    UL18: 59.8e+3
