hists:
  data: multijet_ensemble_average__3
  fit: multijet_ensemble_TH1_basis0__4

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO033827660859918174__1
  ratio_postfit: multijet_ensemble_TH1_basis0ratio_hist0dO7064013318961474__2