hists:
  data: multijet_ensemble_average__31
  fit: multijet_ensemble_TH1_basis4__32

stack:
  Multijet: multijet_ensemble_stack_1


ratio:
  ratio_prefit: multijet_ensembleratio_hist0dO1288144807393503__29
  ratio_postfit: multijet_ensemble_TH1_basis4ratio_hist0dO13116845698025714__30