# template: tag, user
main:
  module: evaluate
  option:
    - --max-evaluators 1
  
dataset:
  - module: HCR.SvB.Eval
    option:
      - --max-workers 8
      - --friends
      -
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@HCR_input
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@JCM_weight
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@FvT_weight
  
model:
  - module: HCR.SvB.ggF.baseline.Eval
    option:
      - --models Final root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/SvB/train/{tag}/result.json

analysis:
  - module: kfold.Merge
    option:
      - --name SvB 


setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/SvB/eval/{tag}/
