# template: tag
main:
  module: analyze
  option:
    - --results 
    - root://cmseos.fnal.gov//store/user/chuyuanl/HH4b/classifier/SvB/train/{tag}/result.json

analysis:
  - module: HCR.LossROC

setting:
  - module: IO
    option:
      - output: root://eosuser.cern.ch//eos/user/c/chuyuan/www/HH4b/classifier/SvB/
        report: {tag}
