# template: tag, user, cernuser
main:
  module: analyze
  option:
    - --results 
    - root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/SvB/train/{tag}/result.json

analysis:
  - module: HCR.LossROC

setting:
  - module: IO
    option:
      - output: root://eosuser.cern.ch//eos/user/{cernuser}/www/HH4b/classifier/SvB/
        report: {tag}
