# template: tag
main:
  module: train
  option:
    - --max-loaders 10
    - --max-trainers 1

model:
  - module: HCR.SvB.ggF.baseline.Train
    option:
      - --kfolds 3
      - --training FixedStep
      - epoch: 20
        bs_init: 1024

setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{{user}}/HH4b/classifier/SvB/train/{tag}/

  - module: torch.DataLoader
    option:
      - num_workers: 4
