name: Mirror from GitLab
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: cms-cmu/coffea4bees
          token: ${{ secrets.GITLAB_TOKEN }}
          ssh-known-hosts: gitlab.cern.ch

      - name: Push to GitHub
        run: |
          git remote add github  https://github.com/alefisico/coffea4bees.git
          git push --mirror github