# template:
# - user: username, usually $USER
# - dataset: name of the dataset (only used in the directory name)

main:
  module: cache
  option:
    - --max-loaders 1
    - --max-writers 10
    - --nchunks 10
    - --shuffle
    - --states label.MultiClass.labels

dataset:
  - module: HCR.FvT.Train
    option:
      - --friends
      -
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@HCR_input
      - root://cmseos.fnal.gov//store/user/{user}/HH4b/friend/friend.json@@JCM_weight
      - --max-workers 8


setting:
  - module: IO
    option:
      - output: root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/FvT/dataset/{dataset}/
