# template:
# - user: username, usually ${USER}
# - cernuser: CERN username in the format of "INITIAL/USERNAME" e.g. c/chuyuan
# - tag: name of the model (only used in the directory name)

main:
  module: analyze
  option:
    - --results 
    - root://cmseos.fnal.gov//store/user/{user}/HH4b/classifier/FvT/train/{tag}/result.json

analysis:
  - module: HCR.LossROC

setting:
  - module: IO
    option:
      - output: root://eosuser.cern.ch//eos/user/{cernuser}/www/HH4b/classifier/FvT/
        report: {tag}
